#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTTTA_WEB_2.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_JTTTA_WEB")]
	public partial class DBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_R_SHIFT(TBL_R_SHIFT instance);
    partial void UpdateTBL_R_SHIFT(TBL_R_SHIFT instance);
    partial void DeleteTBL_R_SHIFT(TBL_R_SHIFT instance);
    partial void InsertTBL_R_MATERIAL(TBL_R_MATERIAL instance);
    partial void UpdateTBL_R_MATERIAL(TBL_R_MATERIAL instance);
    partial void DeleteTBL_R_MATERIAL(TBL_R_MATERIAL instance);
    partial void InsertTBL_R_BERITA_ACARA(TBL_R_BERITA_ACARA instance);
    partial void UpdateTBL_R_BERITA_ACARA(TBL_R_BERITA_ACARA instance);
    partial void DeleteTBL_R_BERITA_ACARA(TBL_R_BERITA_ACARA instance);
    partial void InsertTBL_R_BA_QUALITY(TBL_R_BA_QUALITY instance);
    partial void UpdateTBL_R_BA_QUALITY(TBL_R_BA_QUALITY instance);
    partial void DeleteTBL_R_BA_QUALITY(TBL_R_BA_QUALITY instance);
    partial void InsertTBL_R_ROM(TBL_R_ROM instance);
    partial void UpdateTBL_R_ROM(TBL_R_ROM instance);
    partial void DeleteTBL_R_ROM(TBL_R_ROM instance);
    partial void InsertTBL_R_DESTINATION(TBL_R_DESTINATION instance);
    partial void UpdateTBL_R_DESTINATION(TBL_R_DESTINATION instance);
    partial void DeleteTBL_R_DESTINATION(TBL_R_DESTINATION instance);
    partial void InsertTBL_R_PLANNING(TBL_R_PLANNING instance);
    partial void UpdateTBL_R_PLANNING(TBL_R_PLANNING instance);
    partial void DeleteTBL_R_PLANNING(TBL_R_PLANNING instance);
    partial void InsertTBL_R_LOADER(TBL_R_LOADER instance);
    partial void UpdateTBL_R_LOADER(TBL_R_LOADER instance);
    partial void DeleteTBL_R_LOADER(TBL_R_LOADER instance);
    #endregion
		
		public DBContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_JTTTA_WEBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_R_SHIFT> TBL_R_SHIFTs
		{
			get
			{
				return this.GetTable<TBL_R_SHIFT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_MATERIAL> TBL_R_MATERIALs
		{
			get
			{
				return this.GetTable<TBL_R_MATERIAL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_BERITA_ACARA> TBL_R_BERITA_ACARAs
		{
			get
			{
				return this.GetTable<TBL_R_BERITA_ACARA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_BA_QUALITY> TBL_R_BA_QUALITies
		{
			get
			{
				return this.GetTable<TBL_R_BA_QUALITY>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_ROM> TBL_R_ROMs
		{
			get
			{
				return this.GetTable<TBL_R_ROM>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_DESTINATION> TBL_R_DESTINATIONs
		{
			get
			{
				return this.GetTable<TBL_R_DESTINATION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_PLANNING> TBL_R_PLANNINGs
		{
			get
			{
				return this.GetTable<TBL_R_PLANNING>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_LOADER> TBL_R_LOADERs
		{
			get
			{
				return this.GetTable<TBL_R_LOADER>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_INDEX_PLANNING> VW_R_INDEX_PLANNINGs
		{
			get
			{
				return this.GetTable<VW_R_INDEX_PLANNING>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_INDEX_LOADER> VW_R_INDEX_LOADERs
		{
			get
			{
				return this.GetTable<VW_R_INDEX_LOADER>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CUFN_CEK_JMLLOADER", IsComposable=true)]
		public System.Nullable<int> CUFN_CEK_JMLLOADER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> jam_awal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> jam_akhir, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string loader)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), jam_awal, jam_akhir, loader).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_SHIFT")]
	public partial class TBL_R_SHIFT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SHIFT_CODE;
		
		private string _SHIFT_NAME;
		
		private string _SHIFT_AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSHIFT_CODEChanging(string value);
    partial void OnSHIFT_CODEChanged();
    partial void OnSHIFT_NAMEChanging(string value);
    partial void OnSHIFT_NAMEChanged();
    partial void OnSHIFT_AKTIFChanging(string value);
    partial void OnSHIFT_AKTIFChanged();
    #endregion
		
		public TBL_R_SHIFT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SHIFT_CODE
		{
			get
			{
				return this._SHIFT_CODE;
			}
			set
			{
				if ((this._SHIFT_CODE != value))
				{
					this.OnSHIFT_CODEChanging(value);
					this.SendPropertyChanging();
					this._SHIFT_CODE = value;
					this.SendPropertyChanged("SHIFT_CODE");
					this.OnSHIFT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SHIFT_NAME
		{
			get
			{
				return this._SHIFT_NAME;
			}
			set
			{
				if ((this._SHIFT_NAME != value))
				{
					this.OnSHIFT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SHIFT_NAME = value;
					this.SendPropertyChanged("SHIFT_NAME");
					this.OnSHIFT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT_AKTIF", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string SHIFT_AKTIF
		{
			get
			{
				return this._SHIFT_AKTIF;
			}
			set
			{
				if ((this._SHIFT_AKTIF != value))
				{
					this.OnSHIFT_AKTIFChanging(value);
					this.SendPropertyChanging();
					this._SHIFT_AKTIF = value;
					this.SendPropertyChanged("SHIFT_AKTIF");
					this.OnSHIFT_AKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_MATERIAL")]
	public partial class TBL_R_MATERIAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATERIAL_CODE;
		
		private string _MATERIAL_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATERIAL_CODEChanging(string value);
    partial void OnMATERIAL_CODEChanged();
    partial void OnMATERIAL_NAMEChanging(string value);
    partial void OnMATERIAL_NAMEChanged();
    #endregion
		
		public TBL_R_MATERIAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIAL_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATERIAL_CODE
		{
			get
			{
				return this._MATERIAL_CODE;
			}
			set
			{
				if ((this._MATERIAL_CODE != value))
				{
					this.OnMATERIAL_CODEChanging(value);
					this.SendPropertyChanging();
					this._MATERIAL_CODE = value;
					this.SendPropertyChanged("MATERIAL_CODE");
					this.OnMATERIAL_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIAL_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MATERIAL_NAME
		{
			get
			{
				return this._MATERIAL_NAME;
			}
			set
			{
				if ((this._MATERIAL_NAME != value))
				{
					this.OnMATERIAL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MATERIAL_NAME = value;
					this.SendPropertyChanged("MATERIAL_NAME");
					this.OnMATERIAL_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_BERITA_ACARA")]
	public partial class TBL_R_BERITA_ACARA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Tanggal;
		
		private string _Rom;
		
		private string _MATERIAL_NAME;
		
		private string _Inventory;
		
		private string _Tm;
		
		private string _Im;
		
		private string _Ash;
		
		private string _Vm;
		
		private string _Fc;
		
		private string _Ts;
		
		private string _Cva;
		
		private string _Cvd;
		
		private string _Rd;
		
		private string _Hgi;
		
		private string _Csn;
		
		private string _Is;
		
		private string _Mc;
		
		private string _Md;
		
		private string _Ml;
		
		private string _Ff;
		
		private string _So;
		
		private string _Pr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnTanggalChanging(string value);
    partial void OnTanggalChanged();
    partial void OnRomChanging(string value);
    partial void OnRomChanged();
    partial void OnMATERIAL_NAMEChanging(string value);
    partial void OnMATERIAL_NAMEChanged();
    partial void OnInventoryChanging(string value);
    partial void OnInventoryChanged();
    partial void OnTmChanging(string value);
    partial void OnTmChanged();
    partial void OnImChanging(string value);
    partial void OnImChanged();
    partial void OnAshChanging(string value);
    partial void OnAshChanged();
    partial void OnVmChanging(string value);
    partial void OnVmChanged();
    partial void OnFcChanging(string value);
    partial void OnFcChanged();
    partial void OnTsChanging(string value);
    partial void OnTsChanged();
    partial void OnCvaChanging(string value);
    partial void OnCvaChanged();
    partial void OnCvdChanging(string value);
    partial void OnCvdChanged();
    partial void OnRdChanging(string value);
    partial void OnRdChanged();
    partial void OnHgiChanging(string value);
    partial void OnHgiChanged();
    partial void OnCsnChanging(string value);
    partial void OnCsnChanged();
    partial void OnIsChanging(string value);
    partial void OnIsChanged();
    partial void OnMcChanging(string value);
    partial void OnMcChanged();
    partial void OnMdChanging(string value);
    partial void OnMdChanged();
    partial void OnMlChanging(string value);
    partial void OnMlChanged();
    partial void OnFfChanging(string value);
    partial void OnFfChanged();
    partial void OnSoChanging(string value);
    partial void OnSoChanged();
    partial void OnPrChanging(string value);
    partial void OnPrChanged();
    #endregion
		
		public TBL_R_BERITA_ACARA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal", DbType="NChar(10)")]
		public string Tanggal
		{
			get
			{
				return this._Tanggal;
			}
			set
			{
				if ((this._Tanggal != value))
				{
					this.OnTanggalChanging(value);
					this.SendPropertyChanging();
					this._Tanggal = value;
					this.SendPropertyChanged("Tanggal");
					this.OnTanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rom", DbType="NChar(10)")]
		public string Rom
		{
			get
			{
				return this._Rom;
			}
			set
			{
				if ((this._Rom != value))
				{
					this.OnRomChanging(value);
					this.SendPropertyChanging();
					this._Rom = value;
					this.SendPropertyChanged("Rom");
					this.OnRomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIAL_NAME", DbType="NChar(10)")]
		public string MATERIAL_NAME
		{
			get
			{
				return this._MATERIAL_NAME;
			}
			set
			{
				if ((this._MATERIAL_NAME != value))
				{
					this.OnMATERIAL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MATERIAL_NAME = value;
					this.SendPropertyChanged("MATERIAL_NAME");
					this.OnMATERIAL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory", DbType="NChar(10)")]
		public string Inventory
		{
			get
			{
				return this._Inventory;
			}
			set
			{
				if ((this._Inventory != value))
				{
					this.OnInventoryChanging(value);
					this.SendPropertyChanging();
					this._Inventory = value;
					this.SendPropertyChanged("Inventory");
					this.OnInventoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tm", DbType="NChar(10)")]
		public string Tm
		{
			get
			{
				return this._Tm;
			}
			set
			{
				if ((this._Tm != value))
				{
					this.OnTmChanging(value);
					this.SendPropertyChanging();
					this._Tm = value;
					this.SendPropertyChanged("Tm");
					this.OnTmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Im", DbType="NChar(10)")]
		public string Im
		{
			get
			{
				return this._Im;
			}
			set
			{
				if ((this._Im != value))
				{
					this.OnImChanging(value);
					this.SendPropertyChanging();
					this._Im = value;
					this.SendPropertyChanged("Im");
					this.OnImChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ash", DbType="NChar(10)")]
		public string Ash
		{
			get
			{
				return this._Ash;
			}
			set
			{
				if ((this._Ash != value))
				{
					this.OnAshChanging(value);
					this.SendPropertyChanging();
					this._Ash = value;
					this.SendPropertyChanged("Ash");
					this.OnAshChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vm", DbType="NChar(10)")]
		public string Vm
		{
			get
			{
				return this._Vm;
			}
			set
			{
				if ((this._Vm != value))
				{
					this.OnVmChanging(value);
					this.SendPropertyChanging();
					this._Vm = value;
					this.SendPropertyChanged("Vm");
					this.OnVmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fc", DbType="NChar(10)")]
		public string Fc
		{
			get
			{
				return this._Fc;
			}
			set
			{
				if ((this._Fc != value))
				{
					this.OnFcChanging(value);
					this.SendPropertyChanging();
					this._Fc = value;
					this.SendPropertyChanged("Fc");
					this.OnFcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ts", DbType="NChar(10)")]
		public string Ts
		{
			get
			{
				return this._Ts;
			}
			set
			{
				if ((this._Ts != value))
				{
					this.OnTsChanging(value);
					this.SendPropertyChanging();
					this._Ts = value;
					this.SendPropertyChanged("Ts");
					this.OnTsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cva", DbType="NChar(10)")]
		public string Cva
		{
			get
			{
				return this._Cva;
			}
			set
			{
				if ((this._Cva != value))
				{
					this.OnCvaChanging(value);
					this.SendPropertyChanging();
					this._Cva = value;
					this.SendPropertyChanged("Cva");
					this.OnCvaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cvd", DbType="NChar(10)")]
		public string Cvd
		{
			get
			{
				return this._Cvd;
			}
			set
			{
				if ((this._Cvd != value))
				{
					this.OnCvdChanging(value);
					this.SendPropertyChanging();
					this._Cvd = value;
					this.SendPropertyChanged("Cvd");
					this.OnCvdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rd", DbType="NChar(10)")]
		public string Rd
		{
			get
			{
				return this._Rd;
			}
			set
			{
				if ((this._Rd != value))
				{
					this.OnRdChanging(value);
					this.SendPropertyChanging();
					this._Rd = value;
					this.SendPropertyChanged("Rd");
					this.OnRdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hgi", DbType="NChar(10)")]
		public string Hgi
		{
			get
			{
				return this._Hgi;
			}
			set
			{
				if ((this._Hgi != value))
				{
					this.OnHgiChanging(value);
					this.SendPropertyChanging();
					this._Hgi = value;
					this.SendPropertyChanged("Hgi");
					this.OnHgiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Csn", DbType="NChar(10)")]
		public string Csn
		{
			get
			{
				return this._Csn;
			}
			set
			{
				if ((this._Csn != value))
				{
					this.OnCsnChanging(value);
					this.SendPropertyChanging();
					this._Csn = value;
					this.SendPropertyChanged("Csn");
					this.OnCsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Is]", Storage="_Is", DbType="NChar(10)")]
		public string Is
		{
			get
			{
				return this._Is;
			}
			set
			{
				if ((this._Is != value))
				{
					this.OnIsChanging(value);
					this.SendPropertyChanging();
					this._Is = value;
					this.SendPropertyChanged("Is");
					this.OnIsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mc", DbType="NChar(10)")]
		public string Mc
		{
			get
			{
				return this._Mc;
			}
			set
			{
				if ((this._Mc != value))
				{
					this.OnMcChanging(value);
					this.SendPropertyChanging();
					this._Mc = value;
					this.SendPropertyChanged("Mc");
					this.OnMcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Md", DbType="NChar(10)")]
		public string Md
		{
			get
			{
				return this._Md;
			}
			set
			{
				if ((this._Md != value))
				{
					this.OnMdChanging(value);
					this.SendPropertyChanging();
					this._Md = value;
					this.SendPropertyChanged("Md");
					this.OnMdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ml", DbType="NChar(10)")]
		public string Ml
		{
			get
			{
				return this._Ml;
			}
			set
			{
				if ((this._Ml != value))
				{
					this.OnMlChanging(value);
					this.SendPropertyChanging();
					this._Ml = value;
					this.SendPropertyChanged("Ml");
					this.OnMlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ff", DbType="NChar(10)")]
		public string Ff
		{
			get
			{
				return this._Ff;
			}
			set
			{
				if ((this._Ff != value))
				{
					this.OnFfChanging(value);
					this.SendPropertyChanging();
					this._Ff = value;
					this.SendPropertyChanged("Ff");
					this.OnFfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So", DbType="NChar(10)")]
		public string So
		{
			get
			{
				return this._So;
			}
			set
			{
				if ((this._So != value))
				{
					this.OnSoChanging(value);
					this.SendPropertyChanging();
					this._So = value;
					this.SendPropertyChanged("So");
					this.OnSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pr", DbType="NChar(10)")]
		public string Pr
		{
			get
			{
				return this._Pr;
			}
			set
			{
				if ((this._Pr != value))
				{
					this.OnPrChanging(value);
					this.SendPropertyChanging();
					this._Pr = value;
					this.SendPropertyChanged("Pr");
					this.OnPrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_BA_QUALITY")]
	public partial class TBL_R_BA_QUALITY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tanggal;
		
		private string _ROM_NAME;
		
		private string _MATERIAL_NAME;
		
		private string _TM;
		
		private string _IM;
		
		private string _ASH;
		
		private string _VM;
		
		private string _FC;
		
		private string _TS;
		
		private string _CVA;
		
		private string _CVD;
		
		private string _RD;
		
		private string _HGI;
		
		private string _CSN;
		
		private string _IS;
		
		private string _MC;
		
		private string _MD;
		
		private string _ML;
		
		private string _FF;
		
		private string _SO;
		
		private string _PR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTanggalChanging(string value);
    partial void OnTanggalChanged();
    partial void OnROM_NAMEChanging(string value);
    partial void OnROM_NAMEChanged();
    partial void OnMATERIAL_NAMEChanging(string value);
    partial void OnMATERIAL_NAMEChanged();
    partial void OnTMChanging(string value);
    partial void OnTMChanged();
    partial void OnIMChanging(string value);
    partial void OnIMChanged();
    partial void OnASHChanging(string value);
    partial void OnASHChanged();
    partial void OnVMChanging(string value);
    partial void OnVMChanged();
    partial void OnFCChanging(string value);
    partial void OnFCChanged();
    partial void OnTSChanging(string value);
    partial void OnTSChanged();
    partial void OnCVAChanging(string value);
    partial void OnCVAChanged();
    partial void OnCVDChanging(string value);
    partial void OnCVDChanged();
    partial void OnRDChanging(string value);
    partial void OnRDChanged();
    partial void OnHGIChanging(string value);
    partial void OnHGIChanged();
    partial void OnCSNChanging(string value);
    partial void OnCSNChanged();
    partial void OnISChanging(string value);
    partial void OnISChanged();
    partial void OnMCChanging(string value);
    partial void OnMCChanged();
    partial void OnMDChanging(string value);
    partial void OnMDChanged();
    partial void OnMLChanging(string value);
    partial void OnMLChanged();
    partial void OnFFChanging(string value);
    partial void OnFFChanged();
    partial void OnSOChanging(string value);
    partial void OnSOChanged();
    partial void OnPRChanging(string value);
    partial void OnPRChanged();
    #endregion
		
		public TBL_R_BA_QUALITY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal", DbType="NChar(10)")]
		public string Tanggal
		{
			get
			{
				return this._Tanggal;
			}
			set
			{
				if ((this._Tanggal != value))
				{
					this.OnTanggalChanging(value);
					this.SendPropertyChanging();
					this._Tanggal = value;
					this.SendPropertyChanged("Tanggal");
					this.OnTanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROM_NAME", DbType="NChar(30)")]
		public string ROM_NAME
		{
			get
			{
				return this._ROM_NAME;
			}
			set
			{
				if ((this._ROM_NAME != value))
				{
					this.OnROM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ROM_NAME = value;
					this.SendPropertyChanged("ROM_NAME");
					this.OnROM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIAL_NAME", DbType="NChar(30)")]
		public string MATERIAL_NAME
		{
			get
			{
				return this._MATERIAL_NAME;
			}
			set
			{
				if ((this._MATERIAL_NAME != value))
				{
					this.OnMATERIAL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MATERIAL_NAME = value;
					this.SendPropertyChanged("MATERIAL_NAME");
					this.OnMATERIAL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TM", DbType="NChar(10)")]
		public string TM
		{
			get
			{
				return this._TM;
			}
			set
			{
				if ((this._TM != value))
				{
					this.OnTMChanging(value);
					this.SendPropertyChanging();
					this._TM = value;
					this.SendPropertyChanged("TM");
					this.OnTMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IM", DbType="NChar(10)")]
		public string IM
		{
			get
			{
				return this._IM;
			}
			set
			{
				if ((this._IM != value))
				{
					this.OnIMChanging(value);
					this.SendPropertyChanging();
					this._IM = value;
					this.SendPropertyChanged("IM");
					this.OnIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASH", DbType="NChar(10)")]
		public string ASH
		{
			get
			{
				return this._ASH;
			}
			set
			{
				if ((this._ASH != value))
				{
					this.OnASHChanging(value);
					this.SendPropertyChanging();
					this._ASH = value;
					this.SendPropertyChanged("ASH");
					this.OnASHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VM", DbType="NChar(10)")]
		public string VM
		{
			get
			{
				return this._VM;
			}
			set
			{
				if ((this._VM != value))
				{
					this.OnVMChanging(value);
					this.SendPropertyChanging();
					this._VM = value;
					this.SendPropertyChanged("VM");
					this.OnVMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FC", DbType="NChar(10)")]
		public string FC
		{
			get
			{
				return this._FC;
			}
			set
			{
				if ((this._FC != value))
				{
					this.OnFCChanging(value);
					this.SendPropertyChanging();
					this._FC = value;
					this.SendPropertyChanged("FC");
					this.OnFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="NChar(10)")]
		public string TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVA", DbType="NChar(10)")]
		public string CVA
		{
			get
			{
				return this._CVA;
			}
			set
			{
				if ((this._CVA != value))
				{
					this.OnCVAChanging(value);
					this.SendPropertyChanging();
					this._CVA = value;
					this.SendPropertyChanged("CVA");
					this.OnCVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVD", DbType="NChar(10)")]
		public string CVD
		{
			get
			{
				return this._CVD;
			}
			set
			{
				if ((this._CVD != value))
				{
					this.OnCVDChanging(value);
					this.SendPropertyChanging();
					this._CVD = value;
					this.SendPropertyChanged("CVD");
					this.OnCVDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RD", DbType="NChar(10)")]
		public string RD
		{
			get
			{
				return this._RD;
			}
			set
			{
				if ((this._RD != value))
				{
					this.OnRDChanging(value);
					this.SendPropertyChanging();
					this._RD = value;
					this.SendPropertyChanged("RD");
					this.OnRDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HGI", DbType="NChar(10)")]
		public string HGI
		{
			get
			{
				return this._HGI;
			}
			set
			{
				if ((this._HGI != value))
				{
					this.OnHGIChanging(value);
					this.SendPropertyChanging();
					this._HGI = value;
					this.SendPropertyChanged("HGI");
					this.OnHGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSN", DbType="NChar(10)")]
		public string CSN
		{
			get
			{
				return this._CSN;
			}
			set
			{
				if ((this._CSN != value))
				{
					this.OnCSNChanging(value);
					this.SendPropertyChanging();
					this._CSN = value;
					this.SendPropertyChanged("CSN");
					this.OnCSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[IS]", Storage="_IS", DbType="NChar(10)")]
		public string IS
		{
			get
			{
				return this._IS;
			}
			set
			{
				if ((this._IS != value))
				{
					this.OnISChanging(value);
					this.SendPropertyChanging();
					this._IS = value;
					this.SendPropertyChanged("IS");
					this.OnISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC", DbType="NChar(10)")]
		public string MC
		{
			get
			{
				return this._MC;
			}
			set
			{
				if ((this._MC != value))
				{
					this.OnMCChanging(value);
					this.SendPropertyChanging();
					this._MC = value;
					this.SendPropertyChanged("MC");
					this.OnMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MD", DbType="NChar(10)")]
		public string MD
		{
			get
			{
				return this._MD;
			}
			set
			{
				if ((this._MD != value))
				{
					this.OnMDChanging(value);
					this.SendPropertyChanging();
					this._MD = value;
					this.SendPropertyChanged("MD");
					this.OnMDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ML", DbType="NChar(10)")]
		public string ML
		{
			get
			{
				return this._ML;
			}
			set
			{
				if ((this._ML != value))
				{
					this.OnMLChanging(value);
					this.SendPropertyChanging();
					this._ML = value;
					this.SendPropertyChanged("ML");
					this.OnMLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FF", DbType="NChar(10)")]
		public string FF
		{
			get
			{
				return this._FF;
			}
			set
			{
				if ((this._FF != value))
				{
					this.OnFFChanging(value);
					this.SendPropertyChanging();
					this._FF = value;
					this.SendPropertyChanged("FF");
					this.OnFFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO", DbType="NChar(10)")]
		public string SO
		{
			get
			{
				return this._SO;
			}
			set
			{
				if ((this._SO != value))
				{
					this.OnSOChanging(value);
					this.SendPropertyChanging();
					this._SO = value;
					this.SendPropertyChanged("SO");
					this.OnSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR", DbType="NChar(10)")]
		public string PR
		{
			get
			{
				return this._PR;
			}
			set
			{
				if ((this._PR != value))
				{
					this.OnPRChanging(value);
					this.SendPropertyChanging();
					this._PR = value;
					this.SendPropertyChanged("PR");
					this.OnPRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_ROM")]
	public partial class TBL_R_ROM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ROM_CODE;
		
		private string _ROM_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnROM_CODEChanging(string value);
    partial void OnROM_CODEChanged();
    partial void OnROM_NAMEChanging(string value);
    partial void OnROM_NAMEChanged();
    #endregion
		
		public TBL_R_ROM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROM_CODE", DbType="VarChar(50)")]
		public string ROM_CODE
		{
			get
			{
				return this._ROM_CODE;
			}
			set
			{
				if ((this._ROM_CODE != value))
				{
					this.OnROM_CODEChanging(value);
					this.SendPropertyChanging();
					this._ROM_CODE = value;
					this.SendPropertyChanged("ROM_CODE");
					this.OnROM_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROM_NAME", DbType="VarChar(50)")]
		public string ROM_NAME
		{
			get
			{
				return this._ROM_NAME;
			}
			set
			{
				if ((this._ROM_NAME != value))
				{
					this.OnROM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ROM_NAME = value;
					this.SendPropertyChanged("ROM_NAME");
					this.OnROM_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_DESTINATION")]
	public partial class TBL_R_DESTINATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DEST_CODE;
		
		private string _DEST_NAME;
		
		private string _DEST_CPP;
		
		private string _DEST_TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDEST_CODEChanging(string value);
    partial void OnDEST_CODEChanged();
    partial void OnDEST_NAMEChanging(string value);
    partial void OnDEST_NAMEChanged();
    partial void OnDEST_CPPChanging(string value);
    partial void OnDEST_CPPChanged();
    partial void OnDEST_TYPEChanging(string value);
    partial void OnDEST_TYPEChanged();
    #endregion
		
		public TBL_R_DESTINATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DEST_CODE
		{
			get
			{
				return this._DEST_CODE;
			}
			set
			{
				if ((this._DEST_CODE != value))
				{
					this.OnDEST_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEST_CODE = value;
					this.SendPropertyChanged("DEST_CODE");
					this.OnDEST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DEST_NAME
		{
			get
			{
				return this._DEST_NAME;
			}
			set
			{
				if ((this._DEST_NAME != value))
				{
					this.OnDEST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DEST_NAME = value;
					this.SendPropertyChanged("DEST_NAME");
					this.OnDEST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_CPP", DbType="VarChar(10)")]
		public string DEST_CPP
		{
			get
			{
				return this._DEST_CPP;
			}
			set
			{
				if ((this._DEST_CPP != value))
				{
					this.OnDEST_CPPChanging(value);
					this.SendPropertyChanging();
					this._DEST_CPP = value;
					this.SendPropertyChanged("DEST_CPP");
					this.OnDEST_CPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST_TYPE", DbType="VarChar(5)")]
		public string DEST_TYPE
		{
			get
			{
				return this._DEST_TYPE;
			}
			set
			{
				if ((this._DEST_TYPE != value))
				{
					this.OnDEST_TYPEChanging(value);
					this.SendPropertyChanging();
					this._DEST_TYPE = value;
					this.SendPropertyChanged("DEST_TYPE");
					this.OnDEST_TYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_PLANNING")]
	public partial class TBL_R_PLANNING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PLAN_ID;
		
		private string _PLAN_TANGGAL;
		
		private string _PLAN_SHIFT;
		
		private System.Nullable<System.DateTime> _PLAN_START_TIME;
		
		private System.Nullable<System.DateTime> _PLAN_END_TIME;
		
		private string _PLAN_SEAM;
		
		private string _PLAN_BLOCK;
		
		private string _PLAN_STRIP;
		
		private string _PLAN_ELEVASI;
		
		private string _PLAN_MATERIAL;
		
		private string _PLAN_DEST;
		
		private string _PLAN_INVENTORY;
		
		private int _PLAN_ASH;
		
		private int _PLAN_TM;
		
		private System.Nullable<int> _PLAN_IM;
		
		private System.Nullable<int> _PLAN_VM;
		
		private System.Nullable<int> _PLAN_FC;
		
		private System.Nullable<int> _PLAN_TS;
		
		private System.Nullable<int> _PLAN_CVA;
		
		private System.Nullable<int> _PLAN_CVD;
		
		private System.Nullable<int> _PLAN_RD;
		
		private System.Nullable<int> _PLAN_HGI;
		
		private System.Nullable<int> _PLAN_CSN;
		
		private System.Nullable<int> _PLAN_IS;
		
		private System.Nullable<int> _PLAN_MC;
		
		private System.Nullable<int> _PLAN_MD;
		
		private System.Nullable<int> _PLAN_ML;
		
		private System.Nullable<int> _PLAN_FF;
		
		private System.Nullable<int> _PLAN_SO;
		
		private System.Nullable<int> _PLAN_PR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPLAN_IDChanging(string value);
    partial void OnPLAN_IDChanged();
    partial void OnPLAN_TANGGALChanging(string value);
    partial void OnPLAN_TANGGALChanged();
    partial void OnPLAN_SHIFTChanging(string value);
    partial void OnPLAN_SHIFTChanged();
    partial void OnPLAN_START_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnPLAN_START_TIMEChanged();
    partial void OnPLAN_END_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnPLAN_END_TIMEChanged();
    partial void OnPLAN_SEAMChanging(string value);
    partial void OnPLAN_SEAMChanged();
    partial void OnPLAN_BLOCKChanging(string value);
    partial void OnPLAN_BLOCKChanged();
    partial void OnPLAN_STRIPChanging(string value);
    partial void OnPLAN_STRIPChanged();
    partial void OnPLAN_ELEVASIChanging(string value);
    partial void OnPLAN_ELEVASIChanged();
    partial void OnPLAN_MATERIALChanging(string value);
    partial void OnPLAN_MATERIALChanged();
    partial void OnPLAN_DESTChanging(string value);
    partial void OnPLAN_DESTChanged();
    partial void OnPLAN_INVENTORYChanging(string value);
    partial void OnPLAN_INVENTORYChanged();
    partial void OnPLAN_ASHChanging(int value);
    partial void OnPLAN_ASHChanged();
    partial void OnPLAN_TMChanging(int value);
    partial void OnPLAN_TMChanged();
    partial void OnPLAN_IMChanging(System.Nullable<int> value);
    partial void OnPLAN_IMChanged();
    partial void OnPLAN_VMChanging(System.Nullable<int> value);
    partial void OnPLAN_VMChanged();
    partial void OnPLAN_FCChanging(System.Nullable<int> value);
    partial void OnPLAN_FCChanged();
    partial void OnPLAN_TSChanging(System.Nullable<int> value);
    partial void OnPLAN_TSChanged();
    partial void OnPLAN_CVAChanging(System.Nullable<int> value);
    partial void OnPLAN_CVAChanged();
    partial void OnPLAN_CVDChanging(System.Nullable<int> value);
    partial void OnPLAN_CVDChanged();
    partial void OnPLAN_RDChanging(System.Nullable<int> value);
    partial void OnPLAN_RDChanged();
    partial void OnPLAN_HGIChanging(System.Nullable<int> value);
    partial void OnPLAN_HGIChanged();
    partial void OnPLAN_CSNChanging(System.Nullable<int> value);
    partial void OnPLAN_CSNChanged();
    partial void OnPLAN_ISChanging(System.Nullable<int> value);
    partial void OnPLAN_ISChanged();
    partial void OnPLAN_MCChanging(System.Nullable<int> value);
    partial void OnPLAN_MCChanged();
    partial void OnPLAN_MDChanging(System.Nullable<int> value);
    partial void OnPLAN_MDChanged();
    partial void OnPLAN_MLChanging(System.Nullable<int> value);
    partial void OnPLAN_MLChanged();
    partial void OnPLAN_FFChanging(System.Nullable<int> value);
    partial void OnPLAN_FFChanged();
    partial void OnPLAN_SOChanging(System.Nullable<int> value);
    partial void OnPLAN_SOChanged();
    partial void OnPLAN_PRChanging(System.Nullable<int> value);
    partial void OnPLAN_PRChanged();
    #endregion
		
		public TBL_R_PLANNING()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PLAN_ID
		{
			get
			{
				return this._PLAN_ID;
			}
			set
			{
				if ((this._PLAN_ID != value))
				{
					this.OnPLAN_IDChanging(value);
					this.SendPropertyChanging();
					this._PLAN_ID = value;
					this.SendPropertyChanged("PLAN_ID");
					this.OnPLAN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_TANGGAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_TANGGAL
		{
			get
			{
				return this._PLAN_TANGGAL;
			}
			set
			{
				if ((this._PLAN_TANGGAL != value))
				{
					this.OnPLAN_TANGGALChanging(value);
					this.SendPropertyChanging();
					this._PLAN_TANGGAL = value;
					this.SendPropertyChanged("PLAN_TANGGAL");
					this.OnPLAN_TANGGALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_SHIFT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_SHIFT
		{
			get
			{
				return this._PLAN_SHIFT;
			}
			set
			{
				if ((this._PLAN_SHIFT != value))
				{
					this.OnPLAN_SHIFTChanging(value);
					this.SendPropertyChanging();
					this._PLAN_SHIFT = value;
					this.SendPropertyChanged("PLAN_SHIFT");
					this.OnPLAN_SHIFTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_START_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_START_TIME
		{
			get
			{
				return this._PLAN_START_TIME;
			}
			set
			{
				if ((this._PLAN_START_TIME != value))
				{
					this.OnPLAN_START_TIMEChanging(value);
					this.SendPropertyChanging();
					this._PLAN_START_TIME = value;
					this.SendPropertyChanged("PLAN_START_TIME");
					this.OnPLAN_START_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_END_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_END_TIME
		{
			get
			{
				return this._PLAN_END_TIME;
			}
			set
			{
				if ((this._PLAN_END_TIME != value))
				{
					this.OnPLAN_END_TIMEChanging(value);
					this.SendPropertyChanging();
					this._PLAN_END_TIME = value;
					this.SendPropertyChanged("PLAN_END_TIME");
					this.OnPLAN_END_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_SEAM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_SEAM
		{
			get
			{
				return this._PLAN_SEAM;
			}
			set
			{
				if ((this._PLAN_SEAM != value))
				{
					this.OnPLAN_SEAMChanging(value);
					this.SendPropertyChanging();
					this._PLAN_SEAM = value;
					this.SendPropertyChanged("PLAN_SEAM");
					this.OnPLAN_SEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_BLOCK", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_BLOCK
		{
			get
			{
				return this._PLAN_BLOCK;
			}
			set
			{
				if ((this._PLAN_BLOCK != value))
				{
					this.OnPLAN_BLOCKChanging(value);
					this.SendPropertyChanging();
					this._PLAN_BLOCK = value;
					this.SendPropertyChanged("PLAN_BLOCK");
					this.OnPLAN_BLOCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_STRIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_STRIP
		{
			get
			{
				return this._PLAN_STRIP;
			}
			set
			{
				if ((this._PLAN_STRIP != value))
				{
					this.OnPLAN_STRIPChanging(value);
					this.SendPropertyChanging();
					this._PLAN_STRIP = value;
					this.SendPropertyChanged("PLAN_STRIP");
					this.OnPLAN_STRIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ELEVASI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_ELEVASI
		{
			get
			{
				return this._PLAN_ELEVASI;
			}
			set
			{
				if ((this._PLAN_ELEVASI != value))
				{
					this.OnPLAN_ELEVASIChanging(value);
					this.SendPropertyChanging();
					this._PLAN_ELEVASI = value;
					this.SendPropertyChanged("PLAN_ELEVASI");
					this.OnPLAN_ELEVASIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_MATERIAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_MATERIAL
		{
			get
			{
				return this._PLAN_MATERIAL;
			}
			set
			{
				if ((this._PLAN_MATERIAL != value))
				{
					this.OnPLAN_MATERIALChanging(value);
					this.SendPropertyChanging();
					this._PLAN_MATERIAL = value;
					this.SendPropertyChanged("PLAN_MATERIAL");
					this.OnPLAN_MATERIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_DEST", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_DEST
		{
			get
			{
				return this._PLAN_DEST;
			}
			set
			{
				if ((this._PLAN_DEST != value))
				{
					this.OnPLAN_DESTChanging(value);
					this.SendPropertyChanging();
					this._PLAN_DEST = value;
					this.SendPropertyChanged("PLAN_DEST");
					this.OnPLAN_DESTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_INVENTORY", DbType="VarChar(50)")]
		public string PLAN_INVENTORY
		{
			get
			{
				return this._PLAN_INVENTORY;
			}
			set
			{
				if ((this._PLAN_INVENTORY != value))
				{
					this.OnPLAN_INVENTORYChanging(value);
					this.SendPropertyChanging();
					this._PLAN_INVENTORY = value;
					this.SendPropertyChanged("PLAN_INVENTORY");
					this.OnPLAN_INVENTORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ASH", DbType="Int NOT NULL")]
		public int PLAN_ASH
		{
			get
			{
				return this._PLAN_ASH;
			}
			set
			{
				if ((this._PLAN_ASH != value))
				{
					this.OnPLAN_ASHChanging(value);
					this.SendPropertyChanging();
					this._PLAN_ASH = value;
					this.SendPropertyChanged("PLAN_ASH");
					this.OnPLAN_ASHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_TM", DbType="Int NOT NULL")]
		public int PLAN_TM
		{
			get
			{
				return this._PLAN_TM;
			}
			set
			{
				if ((this._PLAN_TM != value))
				{
					this.OnPLAN_TMChanging(value);
					this.SendPropertyChanging();
					this._PLAN_TM = value;
					this.SendPropertyChanged("PLAN_TM");
					this.OnPLAN_TMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_IM", DbType="Int")]
		public System.Nullable<int> PLAN_IM
		{
			get
			{
				return this._PLAN_IM;
			}
			set
			{
				if ((this._PLAN_IM != value))
				{
					this.OnPLAN_IMChanging(value);
					this.SendPropertyChanging();
					this._PLAN_IM = value;
					this.SendPropertyChanged("PLAN_IM");
					this.OnPLAN_IMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_VM", DbType="Int")]
		public System.Nullable<int> PLAN_VM
		{
			get
			{
				return this._PLAN_VM;
			}
			set
			{
				if ((this._PLAN_VM != value))
				{
					this.OnPLAN_VMChanging(value);
					this.SendPropertyChanging();
					this._PLAN_VM = value;
					this.SendPropertyChanged("PLAN_VM");
					this.OnPLAN_VMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_FC", DbType="Int")]
		public System.Nullable<int> PLAN_FC
		{
			get
			{
				return this._PLAN_FC;
			}
			set
			{
				if ((this._PLAN_FC != value))
				{
					this.OnPLAN_FCChanging(value);
					this.SendPropertyChanging();
					this._PLAN_FC = value;
					this.SendPropertyChanged("PLAN_FC");
					this.OnPLAN_FCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_TS", DbType="Int")]
		public System.Nullable<int> PLAN_TS
		{
			get
			{
				return this._PLAN_TS;
			}
			set
			{
				if ((this._PLAN_TS != value))
				{
					this.OnPLAN_TSChanging(value);
					this.SendPropertyChanging();
					this._PLAN_TS = value;
					this.SendPropertyChanged("PLAN_TS");
					this.OnPLAN_TSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_CVA", DbType="Int")]
		public System.Nullable<int> PLAN_CVA
		{
			get
			{
				return this._PLAN_CVA;
			}
			set
			{
				if ((this._PLAN_CVA != value))
				{
					this.OnPLAN_CVAChanging(value);
					this.SendPropertyChanging();
					this._PLAN_CVA = value;
					this.SendPropertyChanged("PLAN_CVA");
					this.OnPLAN_CVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_CVD", DbType="Int")]
		public System.Nullable<int> PLAN_CVD
		{
			get
			{
				return this._PLAN_CVD;
			}
			set
			{
				if ((this._PLAN_CVD != value))
				{
					this.OnPLAN_CVDChanging(value);
					this.SendPropertyChanging();
					this._PLAN_CVD = value;
					this.SendPropertyChanged("PLAN_CVD");
					this.OnPLAN_CVDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_RD", DbType="Int")]
		public System.Nullable<int> PLAN_RD
		{
			get
			{
				return this._PLAN_RD;
			}
			set
			{
				if ((this._PLAN_RD != value))
				{
					this.OnPLAN_RDChanging(value);
					this.SendPropertyChanging();
					this._PLAN_RD = value;
					this.SendPropertyChanged("PLAN_RD");
					this.OnPLAN_RDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_HGI", DbType="Int")]
		public System.Nullable<int> PLAN_HGI
		{
			get
			{
				return this._PLAN_HGI;
			}
			set
			{
				if ((this._PLAN_HGI != value))
				{
					this.OnPLAN_HGIChanging(value);
					this.SendPropertyChanging();
					this._PLAN_HGI = value;
					this.SendPropertyChanged("PLAN_HGI");
					this.OnPLAN_HGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_CSN", DbType="Int")]
		public System.Nullable<int> PLAN_CSN
		{
			get
			{
				return this._PLAN_CSN;
			}
			set
			{
				if ((this._PLAN_CSN != value))
				{
					this.OnPLAN_CSNChanging(value);
					this.SendPropertyChanging();
					this._PLAN_CSN = value;
					this.SendPropertyChanged("PLAN_CSN");
					this.OnPLAN_CSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_IS", DbType="Int")]
		public System.Nullable<int> PLAN_IS
		{
			get
			{
				return this._PLAN_IS;
			}
			set
			{
				if ((this._PLAN_IS != value))
				{
					this.OnPLAN_ISChanging(value);
					this.SendPropertyChanging();
					this._PLAN_IS = value;
					this.SendPropertyChanged("PLAN_IS");
					this.OnPLAN_ISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_MC", DbType="Int")]
		public System.Nullable<int> PLAN_MC
		{
			get
			{
				return this._PLAN_MC;
			}
			set
			{
				if ((this._PLAN_MC != value))
				{
					this.OnPLAN_MCChanging(value);
					this.SendPropertyChanging();
					this._PLAN_MC = value;
					this.SendPropertyChanged("PLAN_MC");
					this.OnPLAN_MCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_MD", DbType="Int")]
		public System.Nullable<int> PLAN_MD
		{
			get
			{
				return this._PLAN_MD;
			}
			set
			{
				if ((this._PLAN_MD != value))
				{
					this.OnPLAN_MDChanging(value);
					this.SendPropertyChanging();
					this._PLAN_MD = value;
					this.SendPropertyChanged("PLAN_MD");
					this.OnPLAN_MDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ML", DbType="Int")]
		public System.Nullable<int> PLAN_ML
		{
			get
			{
				return this._PLAN_ML;
			}
			set
			{
				if ((this._PLAN_ML != value))
				{
					this.OnPLAN_MLChanging(value);
					this.SendPropertyChanging();
					this._PLAN_ML = value;
					this.SendPropertyChanged("PLAN_ML");
					this.OnPLAN_MLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_FF", DbType="Int")]
		public System.Nullable<int> PLAN_FF
		{
			get
			{
				return this._PLAN_FF;
			}
			set
			{
				if ((this._PLAN_FF != value))
				{
					this.OnPLAN_FFChanging(value);
					this.SendPropertyChanging();
					this._PLAN_FF = value;
					this.SendPropertyChanged("PLAN_FF");
					this.OnPLAN_FFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_SO", DbType="Int")]
		public System.Nullable<int> PLAN_SO
		{
			get
			{
				return this._PLAN_SO;
			}
			set
			{
				if ((this._PLAN_SO != value))
				{
					this.OnPLAN_SOChanging(value);
					this.SendPropertyChanging();
					this._PLAN_SO = value;
					this.SendPropertyChanged("PLAN_SO");
					this.OnPLAN_SOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_PR", DbType="Int")]
		public System.Nullable<int> PLAN_PR
		{
			get
			{
				return this._PLAN_PR;
			}
			set
			{
				if ((this._PLAN_PR != value))
				{
					this.OnPLAN_PRChanging(value);
					this.SendPropertyChanging();
					this._PLAN_PR = value;
					this.SendPropertyChanged("PLAN_PR");
					this.OnPLAN_PRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_LOADER")]
	public partial class TBL_R_LOADER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PUNIT_RAW_ID;
		
		private string _PUNIT_PLANNING_ID;
		
		private string _PUNIT_LOADER;
		
		private System.DateTime _PUNIT_STARTDATE;
		
		private System.DateTime _PUNIT_ENDDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPUNIT_RAW_IDChanging(string value);
    partial void OnPUNIT_RAW_IDChanged();
    partial void OnPUNIT_PLANNING_IDChanging(string value);
    partial void OnPUNIT_PLANNING_IDChanged();
    partial void OnPUNIT_LOADERChanging(string value);
    partial void OnPUNIT_LOADERChanged();
    partial void OnPUNIT_STARTDATEChanging(System.DateTime value);
    partial void OnPUNIT_STARTDATEChanged();
    partial void OnPUNIT_ENDDATEChanging(System.DateTime value);
    partial void OnPUNIT_ENDDATEChanged();
    #endregion
		
		public TBL_R_LOADER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_RAW_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PUNIT_RAW_ID
		{
			get
			{
				return this._PUNIT_RAW_ID;
			}
			set
			{
				if ((this._PUNIT_RAW_ID != value))
				{
					this.OnPUNIT_RAW_IDChanging(value);
					this.SendPropertyChanging();
					this._PUNIT_RAW_ID = value;
					this.SendPropertyChanged("PUNIT_RAW_ID");
					this.OnPUNIT_RAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_PLANNING_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PUNIT_PLANNING_ID
		{
			get
			{
				return this._PUNIT_PLANNING_ID;
			}
			set
			{
				if ((this._PUNIT_PLANNING_ID != value))
				{
					this.OnPUNIT_PLANNING_IDChanging(value);
					this.SendPropertyChanging();
					this._PUNIT_PLANNING_ID = value;
					this.SendPropertyChanged("PUNIT_PLANNING_ID");
					this.OnPUNIT_PLANNING_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_LOADER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PUNIT_LOADER
		{
			get
			{
				return this._PUNIT_LOADER;
			}
			set
			{
				if ((this._PUNIT_LOADER != value))
				{
					this.OnPUNIT_LOADERChanging(value);
					this.SendPropertyChanging();
					this._PUNIT_LOADER = value;
					this.SendPropertyChanged("PUNIT_LOADER");
					this.OnPUNIT_LOADERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime PUNIT_STARTDATE
		{
			get
			{
				return this._PUNIT_STARTDATE;
			}
			set
			{
				if ((this._PUNIT_STARTDATE != value))
				{
					this.OnPUNIT_STARTDATEChanging(value);
					this.SendPropertyChanging();
					this._PUNIT_STARTDATE = value;
					this.SendPropertyChanged("PUNIT_STARTDATE");
					this.OnPUNIT_STARTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_ENDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime PUNIT_ENDDATE
		{
			get
			{
				return this._PUNIT_ENDDATE;
			}
			set
			{
				if ((this._PUNIT_ENDDATE != value))
				{
					this.OnPUNIT_ENDDATEChanging(value);
					this.SendPropertyChanging();
					this._PUNIT_ENDDATE = value;
					this.SendPropertyChanged("PUNIT_ENDDATE");
					this.OnPUNIT_ENDDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_R_INDEX_PLANNING")]
	public partial class VW_R_INDEX_PLANNING
	{
		
		private string _PLAN_ID;
		
		private string _PLAN_TANGGAL;
		
		private int _IsAktif;
		
		private string _PLAN_SHIFT;
		
		private string _PLAN_SHIFT_NAME;
		
		private System.Nullable<System.DateTime> _PLAN_START_TIME;
		
		private System.Nullable<System.DateTime> _PLAN_END_TIME;
		
		private string _PLAN_SEAM;
		
		private string _PLAN_BLOCK;
		
		private string _PLAN_STRIP;
		
		private string _PLAN_ELEVASI;
		
		private string _PLAN_MATERIAL;
		
		private string _PLAN_MAT_NAME;
		
		private string _PLAN_DEST_NAME;
		
		private string _PLAN_DEST;
		
		private string _PLAN_INVENTORY;
		
		private int _PLAN_ASH;
		
		private int _PLAN_TM;
		
		private System.Nullable<int> _PLAN_IM;
		
		private System.Nullable<int> _PLAN_VM;
		
		private System.Nullable<int> _PLAN_FC;
		
		private System.Nullable<int> _PLAN_TS;
		
		private System.Nullable<int> _PLAN_CVA;
		
		private System.Nullable<int> _PLAN_CVD;
		
		private System.Nullable<int> _PLAN_RD;
		
		private System.Nullable<int> _PLAN_HGI;
		
		private System.Nullable<int> _PLAN_CSN;
		
		private System.Nullable<int> _PLAN_IS;
		
		private System.Nullable<int> _PLAN_MC;
		
		private System.Nullable<int> _PLAN_MD;
		
		private System.Nullable<int> _PLAN_ML;
		
		private System.Nullable<int> _PLAN_FF;
		
		private System.Nullable<int> _PLAN_SO;
		
		private System.Nullable<int> _PLAN_PR;
		
		public VW_R_INDEX_PLANNING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PLAN_ID
		{
			get
			{
				return this._PLAN_ID;
			}
			set
			{
				if ((this._PLAN_ID != value))
				{
					this._PLAN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_TANGGAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_TANGGAL
		{
			get
			{
				return this._PLAN_TANGGAL;
			}
			set
			{
				if ((this._PLAN_TANGGAL != value))
				{
					this._PLAN_TANGGAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAktif", DbType="Int NOT NULL")]
		public int IsAktif
		{
			get
			{
				return this._IsAktif;
			}
			set
			{
				if ((this._IsAktif != value))
				{
					this._IsAktif = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_SHIFT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_SHIFT
		{
			get
			{
				return this._PLAN_SHIFT;
			}
			set
			{
				if ((this._PLAN_SHIFT != value))
				{
					this._PLAN_SHIFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_SHIFT_NAME", DbType="VarChar(20)")]
		public string PLAN_SHIFT_NAME
		{
			get
			{
				return this._PLAN_SHIFT_NAME;
			}
			set
			{
				if ((this._PLAN_SHIFT_NAME != value))
				{
					this._PLAN_SHIFT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_START_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_START_TIME
		{
			get
			{
				return this._PLAN_START_TIME;
			}
			set
			{
				if ((this._PLAN_START_TIME != value))
				{
					this._PLAN_START_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_END_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> PLAN_END_TIME
		{
			get
			{
				return this._PLAN_END_TIME;
			}
			set
			{
				if ((this._PLAN_END_TIME != value))
				{
					this._PLAN_END_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_SEAM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_SEAM
		{
			get
			{
				return this._PLAN_SEAM;
			}
			set
			{
				if ((this._PLAN_SEAM != value))
				{
					this._PLAN_SEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_BLOCK", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_BLOCK
		{
			get
			{
				return this._PLAN_BLOCK;
			}
			set
			{
				if ((this._PLAN_BLOCK != value))
				{
					this._PLAN_BLOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_STRIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_STRIP
		{
			get
			{
				return this._PLAN_STRIP;
			}
			set
			{
				if ((this._PLAN_STRIP != value))
				{
					this._PLAN_STRIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ELEVASI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_ELEVASI
		{
			get
			{
				return this._PLAN_ELEVASI;
			}
			set
			{
				if ((this._PLAN_ELEVASI != value))
				{
					this._PLAN_ELEVASI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_MATERIAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_MATERIAL
		{
			get
			{
				return this._PLAN_MATERIAL;
			}
			set
			{
				if ((this._PLAN_MATERIAL != value))
				{
					this._PLAN_MATERIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_MAT_NAME", DbType="VarChar(30)")]
		public string PLAN_MAT_NAME
		{
			get
			{
				return this._PLAN_MAT_NAME;
			}
			set
			{
				if ((this._PLAN_MAT_NAME != value))
				{
					this._PLAN_MAT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_DEST_NAME", DbType="VarChar(20)")]
		public string PLAN_DEST_NAME
		{
			get
			{
				return this._PLAN_DEST_NAME;
			}
			set
			{
				if ((this._PLAN_DEST_NAME != value))
				{
					this._PLAN_DEST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_DEST", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PLAN_DEST
		{
			get
			{
				return this._PLAN_DEST;
			}
			set
			{
				if ((this._PLAN_DEST != value))
				{
					this._PLAN_DEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_INVENTORY", DbType="VarChar(50)")]
		public string PLAN_INVENTORY
		{
			get
			{
				return this._PLAN_INVENTORY;
			}
			set
			{
				if ((this._PLAN_INVENTORY != value))
				{
					this._PLAN_INVENTORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ASH", DbType="Int NOT NULL")]
		public int PLAN_ASH
		{
			get
			{
				return this._PLAN_ASH;
			}
			set
			{
				if ((this._PLAN_ASH != value))
				{
					this._PLAN_ASH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_TM", DbType="Int NOT NULL")]
		public int PLAN_TM
		{
			get
			{
				return this._PLAN_TM;
			}
			set
			{
				if ((this._PLAN_TM != value))
				{
					this._PLAN_TM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_IM", DbType="Int")]
		public System.Nullable<int> PLAN_IM
		{
			get
			{
				return this._PLAN_IM;
			}
			set
			{
				if ((this._PLAN_IM != value))
				{
					this._PLAN_IM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_VM", DbType="Int")]
		public System.Nullable<int> PLAN_VM
		{
			get
			{
				return this._PLAN_VM;
			}
			set
			{
				if ((this._PLAN_VM != value))
				{
					this._PLAN_VM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_FC", DbType="Int")]
		public System.Nullable<int> PLAN_FC
		{
			get
			{
				return this._PLAN_FC;
			}
			set
			{
				if ((this._PLAN_FC != value))
				{
					this._PLAN_FC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_TS", DbType="Int")]
		public System.Nullable<int> PLAN_TS
		{
			get
			{
				return this._PLAN_TS;
			}
			set
			{
				if ((this._PLAN_TS != value))
				{
					this._PLAN_TS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_CVA", DbType="Int")]
		public System.Nullable<int> PLAN_CVA
		{
			get
			{
				return this._PLAN_CVA;
			}
			set
			{
				if ((this._PLAN_CVA != value))
				{
					this._PLAN_CVA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_CVD", DbType="Int")]
		public System.Nullable<int> PLAN_CVD
		{
			get
			{
				return this._PLAN_CVD;
			}
			set
			{
				if ((this._PLAN_CVD != value))
				{
					this._PLAN_CVD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_RD", DbType="Int")]
		public System.Nullable<int> PLAN_RD
		{
			get
			{
				return this._PLAN_RD;
			}
			set
			{
				if ((this._PLAN_RD != value))
				{
					this._PLAN_RD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_HGI", DbType="Int")]
		public System.Nullable<int> PLAN_HGI
		{
			get
			{
				return this._PLAN_HGI;
			}
			set
			{
				if ((this._PLAN_HGI != value))
				{
					this._PLAN_HGI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_CSN", DbType="Int")]
		public System.Nullable<int> PLAN_CSN
		{
			get
			{
				return this._PLAN_CSN;
			}
			set
			{
				if ((this._PLAN_CSN != value))
				{
					this._PLAN_CSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_IS", DbType="Int")]
		public System.Nullable<int> PLAN_IS
		{
			get
			{
				return this._PLAN_IS;
			}
			set
			{
				if ((this._PLAN_IS != value))
				{
					this._PLAN_IS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_MC", DbType="Int")]
		public System.Nullable<int> PLAN_MC
		{
			get
			{
				return this._PLAN_MC;
			}
			set
			{
				if ((this._PLAN_MC != value))
				{
					this._PLAN_MC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_MD", DbType="Int")]
		public System.Nullable<int> PLAN_MD
		{
			get
			{
				return this._PLAN_MD;
			}
			set
			{
				if ((this._PLAN_MD != value))
				{
					this._PLAN_MD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_ML", DbType="Int")]
		public System.Nullable<int> PLAN_ML
		{
			get
			{
				return this._PLAN_ML;
			}
			set
			{
				if ((this._PLAN_ML != value))
				{
					this._PLAN_ML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_FF", DbType="Int")]
		public System.Nullable<int> PLAN_FF
		{
			get
			{
				return this._PLAN_FF;
			}
			set
			{
				if ((this._PLAN_FF != value))
				{
					this._PLAN_FF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_SO", DbType="Int")]
		public System.Nullable<int> PLAN_SO
		{
			get
			{
				return this._PLAN_SO;
			}
			set
			{
				if ((this._PLAN_SO != value))
				{
					this._PLAN_SO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAN_PR", DbType="Int")]
		public System.Nullable<int> PLAN_PR
		{
			get
			{
				return this._PLAN_PR;
			}
			set
			{
				if ((this._PLAN_PR != value))
				{
					this._PLAN_PR = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_R_INDEX_LOADER")]
	public partial class VW_R_INDEX_LOADER
	{
		
		private string _PUNIT_RAW_ID;
		
		private string _PUNIT_PLANNING_ID;
		
		private string _PUNIT_LOADER;
		
		private System.DateTime _PUNIT_STARTDATE;
		
		private System.DateTime _PUNIT_ENDDATE;
		
		private int _PUNIT_ISACTIVE;
		
		public VW_R_INDEX_LOADER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_RAW_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PUNIT_RAW_ID
		{
			get
			{
				return this._PUNIT_RAW_ID;
			}
			set
			{
				if ((this._PUNIT_RAW_ID != value))
				{
					this._PUNIT_RAW_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_PLANNING_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PUNIT_PLANNING_ID
		{
			get
			{
				return this._PUNIT_PLANNING_ID;
			}
			set
			{
				if ((this._PUNIT_PLANNING_ID != value))
				{
					this._PUNIT_PLANNING_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_LOADER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PUNIT_LOADER
		{
			get
			{
				return this._PUNIT_LOADER;
			}
			set
			{
				if ((this._PUNIT_LOADER != value))
				{
					this._PUNIT_LOADER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime PUNIT_STARTDATE
		{
			get
			{
				return this._PUNIT_STARTDATE;
			}
			set
			{
				if ((this._PUNIT_STARTDATE != value))
				{
					this._PUNIT_STARTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_ENDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime PUNIT_ENDDATE
		{
			get
			{
				return this._PUNIT_ENDDATE;
			}
			set
			{
				if ((this._PUNIT_ENDDATE != value))
				{
					this._PUNIT_ENDDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNIT_ISACTIVE", DbType="Int NOT NULL")]
		public int PUNIT_ISACTIVE
		{
			get
			{
				return this._PUNIT_ISACTIVE;
			}
			set
			{
				if ((this._PUNIT_ISACTIVE != value))
				{
					this._PUNIT_ISACTIVE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
